version: '3.8'

services:

  vaultwarden:
    image: vaultwarden/server:latest
    # ports:
    #   - 85:80
    networks:
      - intranet
    volumes:
      - /mnt/usbhdd/docker-data/vaultwarden/data:/data
    labels:
      # The labels are usefull for Traefik only
      - "traefik.enable=true"
      - "traefik.docker.network=intranet"
      # Get the routes from http
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.phoenixrise.farm`)"

networks:
  intranet:
    external: true