version: "3.8"
services:
  bind9:
    image: mjkaye/bind9-alpine
    ports:
      - 53:53
      - 53:53/udp
    networks:
      - bridge
    volumes:
      - /docker-data/bind9/named.conf:/etc/bind/named.conf
      - /docker-data/bind9/zones:/var/lib/named
      - /docker-data/bind9/log:/var/log/named

networks:
  bridge:
    external: true