# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# Also quickstart at https://hub.docker.com/r/pihole/pihole
version: "3"
services:
  app:
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
    environment:
      TZ: Australia/Sydney
      WEBPASSWORD: P@ssw0rd!
      PIHOLE_DNS_: 10.69.69.254
    # Volumes store your data between container upgrades
    volumes:
      - /docker-data/pihole/etc:/etc/pihole
      - /docker-data/pihole/dnsmasq.d:/etc/dnsmasq.d
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
