version: '3.8'
services:

  wikijs:
    image: linuxserver/wikijs:arm64v8-latest
    networks:
      - intranet
    volumes:
      - /mnt/usbhdd/docker-data/wikijs/config:/config
      - /mnt/usbhdd/docker-data/wikijs/data:/data
    environment:
      PUID: 1001
      PGID: 1001
      TZ: Australia/Sydney
    labels:
      traefik.enable: "true"
      traefik.docker.network: intranet
      traefik.http.routers.books.rule: Host(`wikijs.phoenixrise.farm`)
    
  books:
    image: linuxserver/bookstack:arm64v8-latest
    networks:
      - intranet
    volumes:
      - /mnt/usbhdd/docker-data/bookstack/config:/config
    environment:
      PUID: 1001
      PGID: 1001
      APP_URL: http://books.phoenixrise.farm
      DB_HOST: maria
      DB_USER: wikiman
      DB_PASS: P@ssw0rd!
      DB_DATABASE: bookstack
    labels:
      traefik.enable: "true"
      traefik.docker.network: intranet
      traefik.http.routers.books.rule: Host(`books.phoenixrise.farm`)

networks:
  intranet:
    external: true
